# Generated by Django 5.2.6 on 2025-09-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPokedex', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moves',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='imagemUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
