# Generated by Django 5.2.6 on 2025-09-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPokedex', '0002_delete_moves_pokemon_imagemurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Natures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
