# Generated by Django 5.2.6 on 2025-09-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPokedex', '0003_natures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Natures',
        ),
    ]
