# Generated by Django 5.2.6 on 2025-09-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPokedex', '0004_treinador_delete_natures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
